#+OPTIONS: toc:nil H:10 ':t
#+LaTeX_HEADER: \usepackage{minimal-curriculum-vitae-en}
#+LaTeX: \small
#+TITLE: 庄周

137-7777-8888 / zhou.zhuang@outlook.com / 宋国蒙邑

* 个人简介

战国中期思想家、哲学家、文学家，道家学派代表人物，与老子并称“老庄”。擅
长辩论、写作、游玩、心理疏导。

* 工作经历

** 前309 - 前298
*著书家*                                         \company{故园}

晚境苍凉，独身栖息故园，课徒著书以自遣。其间，与弟子蔺且等，先后游于山
中和雕陵之樊。晚年尝隐居与曹州南华山。宋王偃置太子为王，即宋元君。当在
此年之后，庄子过惠施之墓。曾前往赵国，与赵惠文王说剑。

** 前333 - 前310
*游士*                \company{列国}

南游楚国，并谏阻楚王兴兵伐越。遇见邑人曹商。曹商归自秦国，自我炫耀，讥
之“舐痔得车”。与惠施濠梁之辩，以及“之楚，见空骷髅”，并与之对话。惠施病
故。自此以后，深瞑不言。

** 前344 - 前334
*漆园吏*                       \company{魏国}

漆园为吏。漆园在蒙地，位于今河南商丘东北。与宋人惠施初次见面。惠施稍后
至魏，得到魏惠王信任，擢为国相。我往见，惠施甚恐，我讥之。惠施后有孟诸
之行，大摆排场，鄙视之。宋君剔成弟偃攻袭剔成。剔成奔齐，偃自立为宋君。
此后不久，辞去漆园吏职。

* 教育背景

** 前347 - 前344
*庄子学博士*              \school{宋图书馆}

** 前351 - 前347
*老子学硕士*              \school{周图书馆}

** 前355 - 前351
*园林学本科*              \school{宋国园林学院}

* 技能和证书

在哲学思想上继承和发展了老子“道法自然”的思想观点，使道家真正成为一个学
派，也成为了道家的重要代表人物，与老子并称“道家之祖”。庄子之学其要本归
于老子之言，故著书十余万字，大多都是寓言，如其中的《渔父》《盗跖》《胠
箧》等篇，都是用来辨明老子的主张的。把“贵生”“为我”引向“达生”“忘我”，归
结为天然的“道”“我”合一。《庄子》和《周易》《老子》并称为“三玄”，在哲学
有较高研究价值。

#+latex: \newpage
* 项目经验

** 前309 - 前298
*著书家*                                         \company{故园}

晚境苍凉，独身栖息故园，课徒著书以自遣。其间，与弟子蔺且等，先后游于山
中和雕陵之樊。晚年尝隐居与曹州南华山。宋王偃置太子为王，即宋元君。当在
此年之后，庄子过惠施之墓。曾前往赵国，与赵惠文王说剑。

** 前333 - 前310
*游士*                \company{列国}

南游楚国，并谏阻楚王兴兵伐越。遇见邑人曹商。曹商归自秦国，自我炫耀，讥
之“舐痔得车”。与惠施濠梁之辩，以及“之楚，见空骷髅”，并与之对话。惠施病
故。自此以后，深瞑不言。

** 前344 - 前 334
*漆园吏*                       \company{魏国}

漆园为吏。漆园在蒙地，位于今河南商丘东北。与宋人惠施初次见面。惠施稍后
至魏，得到魏惠王信任，擢为国相。我往见，惠施甚恐，我以“猜意鹓鶵”讥之。
惠施后有孟诸之行，大摆排场，鄙视之。宋君剔成弟偃攻袭剔成。剔成奔齐，偃
自立为宋君。此后不久，辞去漆园吏职。
